# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 01:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_queried', models.URLField()),
                ('last_query_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GitLogDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_id', models.IntegerField(blank=True, null=True)),
                ('repository_name', models.CharField(blank=True, max_length=100, null=True)),
                ('repository_html_url', models.URLField(blank=True, null=True)),
                ('repository_created_at', models.DateTimeField(blank=True, null=True)),
                ('repository_pushed_at', models.DateTimeField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('gitlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comun.GitLog')),
            ],
        ),
    ]
